# Install ElasticSearch with version and configuration mentioned in vars

- name: Check if ES mount exists
  stat:
    path: /data/elasticsearch
  register: es_mount_exists

- debug:
    msg: "ES mount path does exist"
  when: es_mount_exists.stat.exists and es_mount_exists.stat.isdir

- fail:
    msg: "ES mount path does not exist or is not a directory"
  when: es_mount_exists.stat.exists == False or es_mount_exists.stat.isdir == False

...
