---
# Install Kibana 

- name: Begin the setup of the Pre-reqs
  include_tasks: kb_prereqs.yml

- name: Install Kibana
  package:
    name: "{{ kibana_package }}"
    state: present

- name: Ensure Kibana service is started and enabled at boot
  service:
    name: kibana
    state: started
    enabled: true

- name: Check if Kibana Config File Path is in /opt
  stat:
    path: /opt/kibana/config/kibana.yml 
  register: opt_file_path
  ignore_errors: true

- name: Set /opt file path
  set_fact: kibana_config_file_path = "/opt/kibana/config/kibana.yml"  
  when: opt_file_path.stat.exists == True

- name: Check if Kibana Config File Path is in /etc
  stat:
    path: /etc/default/kibana.yml
  register: etc_file_path
  ignore_errors: true

- name: Set /etc file path
  set_fact: kibana_config_file_path = "/etc/default/kibana.yml"
  when: etc_file_path.stat.exists == True and opt_file_path.stat.exists == False

- fail:
    msg: "Kibana config file - kibana.yml path does not exist in /etc or /opt "
  when: etc_file_path.stat.exists == False or opt_file_path.stat.exists == False

- name: Copy Kibana configuration from template
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644

...
