---
# tasks file for postgres
- name: Install Postgres
  package:
    name: postgresql-server
    state: latest

- name: Check If Postgres DB is Initialized
  find:
    paths: /var/lib/pgsql/data/
    file_type: directory
    patterns: "*"
  register: pgdata_files

- name: Initialize Postgres
  command: postgresql-setup initdb
  when: pgdata_files.matched|int == 0

- name: start postgres
  service:
    name: postgresql
    state: started
    enabled: yes
...

