---
# Install packages necessary for ES and Kibana

- name: Install add-apt-repostory
  apt: 
    name: software-properties-common 
    state: latest

- name: Add Oracle Java Repository
  apt_repository: 
    repo: 'ppa:webupd8team/java'

- name: Accept Java 8 License
  debconf: 
    name: 'oracle-java8-installer' 
    question: 'shared/accepted-oracle-license-v1-1' 
    value: 'true' 
    vtype: 'select'

- name: Install Open Java 8 JDK
  package: 
    name: "{{ item }}" 
    state: latest
  loop:
    - openjdk-8-jdk
    - ca-certificates

...
