---
# Install packages necessary for ES and Kibana

- hosts: es_kibana
  gather_facts: false
  any_errors_fatal: true
  become: true
  tasks:
  - name: Install add-apt-repostory
    apt: name=software-properties-common state=latest

  - name: Add Oracle Java Repository
    apt_repository: repo='ppa:webupd8team/java'

  - name: Accept Java 8 License
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 8
    package: 
      name: "{{ item }}" 
      state: latest
    loop:
      - oracle-java8-installer
      - ca-certificates

...
